issue-182
superwerker/superwerker pull request #217
Opened 2021-05-12 11:32 UTC by KiranGosavi

Added condition to check if both features are set before creating resouce.

2021-05-18 09:14 UTC, sbstjn commented
test pipeline worked fine.

2021-05-25 11:28 UTC, s0enke commented
How about we push this `SCPwithSecurityAndBackup` condition down to the `ServiceControlPolicies` stack, so we could leave the special knowledge  ("SCPwithSecurityAndBackup") to the `ServiceControlPolicies` and the superwerker main stack would not need to know implementation details of the `ServiceControlPolicies` stack ([Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter)). The `ServiceControlPolicies` already knows whether SecurityHub and Backup are enabled.

2021-05-25 11:29 UTC, s0enke requested changes
How about we push this SCPwithSecurityAndBackup condition down to the ServiceControlPolicies stack, so we could leave the special knowledge ("SCPwithSecurityAndBackup") to the ServiceControlPolicies and the superwerker main stack would not need to know implementation details of the ServiceControlPolicies stack (Law of Demeter). The ServiceControlPolicies already knows whether SecurityHub and Backup are enabled.

2021-05-25 11:31 UTC, s0enke commented
I would also propose to give more meaningful titles to the PRs and commit messages. E.g. instead of "issue-182" something like "fix: ServiceControlPolicies feature should not fail if neither SecurityHub nor Backup feature are enabled"

2021-06-11 09:36 UTC, s0enke commented
> How about we push this SCPwithSecurityAndBackup condition down to the ServiceControlPolicies stack, so we could leave the special knowledge ("SCPwithSecurityAndBackup") to the ServiceControlPolicies and the superwerker main stack would not need to know implementation details of the ServiceControlPolicies stack (Law of Demeter). The ServiceControlPolicies already knows whether SecurityHub and Backup are enabled.

Actually, you did this in the initial commit 426fb63, so my comment was bogus.

2021-06-11 09:39 UTC, s0enke commented on templates/service-control-policies.yaml
> +    Condition: SCPwithSecurityAndBackup
Maybe rename the condition to a more generic name like `CreateServiceControlPolicy`

2021-06-21 12:13 UTC, s0enke commented
@KiranGosavi thanks! I cleaned up the PR so it only contains your inital commit and a small wording commit from me. Merging now

2021-06-21 12:14 UTC, merged