ADR proposal: AWS Control Tower
superwerker/superwerker pull request #33
Opened 2020-10-08 12:33 UTC by s0enke

2020-10-27 10:01 UTC, yawn requested changes
LGTM*

2020-10-27 10:01 UTC, yawn commented on docs/adrs/nnnn-aws-control-tower.md
> + - [ ] Should we enable additional GuardRails? Overlaps with SH?
Decision: we know they exist but defer the decision (= waiting for CT support and APIs)

2020-10-27 10:01 UTC, yawn commented on docs/adrs/nnnn-aws-control-tower.md
> + - [ ] Should we consider activating/deactivating VPC creation?
Decision: we know they are kinda useless and inconsistent (e.g. multi region setups) but we wait until we build a network feature for this.

2020-10-27 13:50 UTC, s0enke commented on docs/adrs/nnnn-aws-control-tower.md
> + - CT implies additional costs (e.g. Config Rules)
https://github.com/superwerker/superwerker/issues/60

2020-10-27 14:00 UTC, s0enke commented on docs/adrs/nnnn-aws-control-tower.md
> + - [ ] How to handle SSO and Users
TIL:

> The SSOUserEmail can be a new email address, or the email address associated with an existing AWS SSO user. Whichever you choose, this user will have administrative access to the account you're provisioning.

https://docs.aws.amazon.com/controltower/latest/userguide/account-factory.html#provision-as-end-user (edited)

2021-01-04 14:31 UTC, sbstjn commented on docs/adrs/nnnn-aws-control-tower.md
> + - [ ] How to handle SSO and Users
This topic is deferred to #21

2021-01-04 14:36 UTC, merged