build: migrated python script to typescript for Notification Ops Item
superwerker/superwerker pull request #431
Opened 2024-01-23 10:52 UTC by gaudubey

2024-01-23 11:45 UTC, peermuellerxw requested changes

2024-01-23 11:45 UTC, peermuellerxw commented on cdk/package.json
> +    "aws-sdk-client-mock": "^3.0.1",
aws-sdk-client-mock and aws-sdk-client-mock-jest should stay in "devDepencies"

2024-01-23 11:45 UTC, peermuellerxw commented on cdk/src/stacks/notifications.ts
> +      timeout: Duration.minutes(1),
Maybe reduce the timeout? Before it was just 3 seconds, I believe.

2024-01-23 11:45 UTC, peermuellerxw commented on cdk/test/functions/notification-opsitem-created.test.ts
> +    expect(snsClientMock).toReceiveCommandTimes(PublishCommand, 1);
To improve the test even more you could assert that the contents of the PublishCommand that was received actually contain the body and message.

2024-01-24 10:17 UTC, peermuellerxw approved these changes
Looks good. Please rebase/merge from master and I think then this is good to go.

2024-01-24 11:27 UTC, aperov9 requested changes

2024-02-29 22:07 UTC, merged