feat: Added CDK stack for budget
superwerker/superwerker pull request #470
Opened 2024-03-12 20:46 UTC by gaudubey

Created CDK stack for Budget.

2024-03-13 11:29 UTC, peermuellerxw requested changes
Please also add an acceptance for this stack.

2024-03-13 11:29 UTC, peermuellerxw commented on cdk/test/functions/budget.test.ts
> +describe('resources', () => {
I don't see where we actually compare the CFN resources with the ones synthezised from CDK. Such as https://github.com/superwerker/superwerker/blob/6e2af7291a22fe10617963d8321bc308d46c4461/cdk/test/guardduty.test.ts#L67

2024-03-13 11:29 UTC, peermuellerxw commented on cdk/src/stacks/budget.ts
> +      treatMissingData: cw.TreatMissingData.MISSING,
maybe let's keep the original comment here also, do we know in the future why use this setting.

2024-03-15 14:38 UTC, aperov9 commented
main stack LGTM, just take a look at the unit & acceptance tests

2024-04-02 11:07 UTC, peermuellerxw approved these changes

2024-04-02 11:11 UTC, merged